name: CI/CD - Build & Deploy crm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --------------------
      # Build & Push SERVER
      # --------------------
      - name: Build & Push Server Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          platforms: linux/arm64
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/crm-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/crm-server:${{ github.sha }}

      # --------------------
      # Build & Push CLIENT
      # --------------------
      - name: Build & Push Client Image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          platforms: linux/arm64
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/crm-client:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/crm-client:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy docker-compose and nginx to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSh_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

          source: 'docker-compose.yml,client/nginx.conf'
          target: '~/crm'
          strip_components: 0

      - name: Deploy on Oracle VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd ~/crm

            ls -la

            echo "Logging into Docker Hub..."
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

            echo "Pulling latest images..."
            docker compose pull

            echo "Restarting containers..."
            docker compose up -d --force-recreate

            echo "Deployment completed successfully"
